import {historyRecords,historicalCues,openHistory} from './history_v2.js';
import {FilmPipeline} from './film_pipeline.js';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {initAssets,measurements,V} from './geometry.js';
import {createWorld,locations} from './world.js';
import {chapters,shots,chapterAt,shotAt,filmCamera,DURATION,Soundscape} from './timeline.js';
const $=id=>document.getElementById(id),sound=new Soundscape(),keys=new Set();
let renderer,camera,world,controls,pipeline,playing=false,free=false,t=0,anchorT=0,anchorNow=0,speed=1,intro=true,lastChapter=-1,shotInfo=null,gentle=matchMedia('(prefers-reduced-motion: reduce)').matches,frameSamples=[],lastNow=performance.now(),statsNow=0,shaderErrors=[];
$('gentle').checked=gentle;
function fatal(e){console.error(e);$('loading').classList.add('hidden');$('error').classList.remove('hidden');$('errtext').textContent=e?.stack||String(e);playing=false;}
window.addEventListener('error',e=>fatal(e.error||e.message));window.addEventListener('unhandledrejection',e=>fatal(e.reason));
function toast(s){$('toast').textContent=s;$('toast').classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.add('hidden'),2600);}
function currentTime(){return playing?Math.min(DURATION,anchorT+(performance.now()-anchorNow)*.001*speed):t;}
function setPlaying(value){t=currentTime();playing=!!value;if(playing&&t>=DURATION)t=0;anchorT=t;anchorNow=performance.now();$('play').textContent=playing?'Ⅱ Dừng':'▶ Phát';return playing;}
function dismissIntro(){intro=false;$('intro').classList.add('hidden');$('caption').classList.toggle('hidden',!$('subtitles').checked);}
function seek(value){if(!Number.isFinite(value))return;let old=chapterAt(currentTime()).id;t=THREE.MathUtils.clamp(value,0,DURATION);anchorT=t;anchorNow=performance.now();if(free&&old!==chapterAt(t).id){shotInfo=filmCamera(camera,t,gentle);controls.target.copy(shotInfo.target);controls.update();}updateUI();}
function setFree(value){if(free===value)return;dismissIntro();if(value){setPlaying(false);shotInfo=filmCamera(camera,t,gentle);controls.target.copy(shotInfo.target);controls.enabled=true;controls.update();}else{controls.enabled=false;keys.clear();filmCamera(camera,t,gentle);}free=!!value;$('free').textContent=free?'Về góc phim':'Góc tự do';$('free').classList.toggle('active',free);$('freehint').classList.toggle('hidden',!free);$('touchpad').classList.toggle('show',free);$('status').textContent=free?'QUAN SÁT TỰ DO':'PHỤC DỰNG DIỄN GIẢI';}
function fmt(s){s=Math.floor(s);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');}
function updateUI(){let c=chapterAt(t),i=chapters.indexOf(c);$('time').textContent=fmt(t)+' / 03:30';$('scrub').value=t.toFixed(3);if(i!==lastChapter){$('dateline').textContent=c.date;$('place').textContent=c.title;$('description').textContent=c.text;document.querySelectorAll('#chapters button').forEach((b,j)=>b.classList.toggle('active',i===j));lastChapter=i;}if(t>=204){$('place').textContent='Để không quên.';$('description').textContent='Một phục dựng để nhìn lại không gian và hậu quả chiến tranh. Tư liệu, giới hạn và nguồn ảnh nằm trong hồ sơ đi kèm.';}else if(i===lastChapter&&$('place').textContent==='Để không quên.'){$('place').textContent=c.title;$('description').textContent=c.text;}}
function updateHistory(){let id=chapterAt(t).id,h=historyRecords[id],idx=shots.indexOf(shotAt(t));$('description').textContent=historicalCues[idx];$('sourceTag').textContent=id==='air'||id==='port'?'Nguồn: NMUSAF':id==='hospital'?'Nguồn: hồi ức đăng tại Bạch Mai':id==='street'||id==='after'?'Nguồn: VietnamPlus / TTXVN':id==='lake'?'Nguồn: hồ sơ di tích Hà Nội':'Nguồn: BTLSQG · khảo sát cầu';}
function resize(){if(!renderer)return;let w=innerWidth,h=innerHeight;renderer.setSize(w,h,false);pipeline?.resize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}
function setQuality(q){let ratio=q==='high'?Math.min(devicePixelRatio,1.75):q==='low'?.8:Math.min(devicePixelRatio,1);renderer.setPixelRatio(ratio);world.setQuality(q);pipeline?.setQuality(q);let size=q==='high'?2048:1024;if(world.key.shadow.mapSize.x!==size){world.key.shadow.map?.dispose();world.key.shadow.map=null;world.key.shadow.mapSize.set(size,size);}renderer.shadowMap.enabled=q!=='low';resize();$('quality').value=q;}
function download(blob,name){let a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);}
function capture(){draw(0);renderer.domElement.toBlob(b=>{if(b){download(b,`Mien-Bac-1972_${chapterAt(t).id}_${t.toFixed(2)}s.png`);toast('Đã lưu khung hình PNG, không gồm giao diện.');}},'image/png');}
function saveCamera(){download(new Blob([JSON.stringify({version:'1.0',seed:19721218,time:t,location:world.location,free,position:camera.position.toArray(),target:controls.target.toArray(),quaternion:camera.quaternion.toArray(),fov:camera.fov,quality:$('quality').value},null,2)],{type:'application/json'}),'camera_1972.json');toast('Đã lưu camera và thời điểm.');}
function move(dt){if(!free)return;let f=new THREE.Vector3();camera.getWorldDirection(f);let right=f.clone().cross(camera.up).normalize(),v=new THREE.Vector3(),rate=(keys.has('ShiftLeft')||keys.has('ShiftRight')?68:16)*dt;if(keys.has('KeyW'))v.add(f);if(keys.has('KeyS'))v.sub(f);if(keys.has('KeyA'))v.sub(right);if(keys.has('KeyD'))v.add(right);if(keys.has('KeyQ'))v.y-=1;if(keys.has('KeyE'))v.y+=1;if(v.lengthSq()){v.normalize().multiplyScalar(rate);camera.position.add(v);controls.target.add(v);}controls.update();let old=camera.position.clone(),center=V(locations[chapterAt(t).id].center);camera.position.y=THREE.MathUtils.clamp(camera.position.y,.55,350);let d=camera.position.clone().sub(center);if(d.length()>650)camera.position.copy(center).add(d.setLength(650));controls.target.add(camera.position.clone().sub(old));}
function draw(dt){
 let now=performance.now();t=currentTime();if(playing&&t>=DURATION){t=DURATION;playing=false;$('play').textContent='↺ Xem lại';}
 let c=chapterAt(t);world.setLocation(c.id);if(!free){shotInfo=filmCamera(camera,t,gentle);controls.target.copy(shotInfo.target);}else move(Math.min(dt,.05));
 world.update(t,camera,gentle);sound.update(t,c.id,playing,gentle);let shot=shotAt(t),edge=Math.min(t-shot.a,shot.b-t),fade=!intro&&!free&&t>.1&&t<209.8?Math.max(0,1-edge/.33)*.85:0;$('fade').style.opacity=fade.toFixed(3);$('shotname').textContent=free?'GÓC TỰ DO':`${String(shots.indexOf(shot)+1).padStart(2,'0')} / 19 · ${shot.name}`;
 renderer.info.reset();let a=performance.now();pipeline.render(c.id,t);let cpu=performance.now()-a;updateUI();updateHistory();
 if(dt>0&&dt<1){frameSamples.push({ms:dt*1000,cpu,t});if(frameSamples.length>900)frameSamples.shift();}
 if(now-statsNow>500){statsNow=now;let xs=frameSamples.slice(-90).map(f=>f.ms).sort((a,b)=>a-b),avg=xs.reduce((a,b)=>a+b,0)/(xs.length||1),p95=xs[Math.floor(xs.length*.95)]||0;$('debug').textContent=`${world.location} | ${free?'free':'film'} | ${t.toFixed(2)}s\n${(1000/(avg||16.67)).toFixed(0)} fps · p95 ${p95.toFixed(1)} ms\nCPU submit ${cpu.toFixed(1)} ms\nDraw calls ${renderer.info.render.calls}\nTriangles ${renderer.info.render.triangles.toLocaleString()}\nGeometry ${renderer.info.memory.geometries} · Textures ${renderer.info.memory.textures}\n${Math.round(renderer.domElement.width)} × ${Math.round(renderer.domElement.height)}`;}
}
let idleDraw=0;
function animate(now){if(!playing&&!free&&now-idleDraw<200){requestAnimationFrame(animate);return;}idleDraw=now;let dt=(now-lastNow)*.001;lastNow=now;try{draw(dt);}catch(e){fatal(e);return;}requestAnimationFrame(animate);}
function wireUI(){
 chapters.forEach((c,i)=>{let b=document.createElement('button');b.innerHTML=`<span>${String(i+1).padStart(2,'0')}</span>${c.short}`;b.title=c.title;b.onclick=()=>{dismissIntro();seek(c.start+.7);};$('chapters').append(b);});
 $('chapterhistory').onclick=()=>{setPlaying(false);openHistory(chapterAt(t).id);};
 $('start').onclick=()=>{dismissIntro();setFree(false);seek(0);setPlaying(true);};$('explore').onclick=()=>setFree(true);$('play').onclick=()=>{dismissIntro();setPlaying(!playing);};$('back').onclick=()=>{dismissIntro();seek(currentTime()-5);};$('forward').onclick=()=>{dismissIntro();seek(currentTime()+5);};$('free').onclick=()=>setFree(!free);$('scrub').oninput=e=>{dismissIntro();seek(Number(e.target.value));};$('speed').onchange=e=>{t=currentTime();anchorT=t;anchorNow=performance.now();speed=Number(e.target.value);};$('quality').onchange=e=>setQuality(e.target.value);
 $('gentle').onchange=e=>gentle=e.target.checked;$('subtitles').onchange=e=>$('caption').classList.toggle('hidden',intro||!e.target.checked);$('stats').onchange=e=>$('debug').classList.toggle('hidden',!e.target.checked);$('capture').onclick=capture;$('hide').onclick=()=>document.body.classList.toggle('hideui');$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(e){toast('Trình duyệt không cho phép toàn màn hình ở ngữ cảnh này.');}};
 $('audio').onclick=async()=>{try{let on=await sound.toggle();$('audio').textContent=on?'Âm: bật':'Âm: tắt';$('audio').classList.toggle('active',on);}catch(e){toast(e.message);}};
 for(let[n,d]of[['archive','archiveDialog'],['help','helpDialog']])$(n).onclick=()=>{setPlaying(false);$(d).showModal();};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){let r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
 document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(free&&['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','ShiftLeft','ShiftRight'].includes(e.code)){keys.add(e.code);e.preventDefault();return;}if(e.repeat)return;switch(e.code){case'Space':e.preventDefault();dismissIntro();setPlaying(!playing);break;case'ArrowLeft':e.preventDefault();dismissIntro();seek(currentTime()-5);break;case'ArrowRight':e.preventDefault();dismissIntro();seek(currentTime()+5);break;case'Comma':case'Period':e.preventDefault();setPlaying(false);dismissIntro();seek(t+(e.code==='Comma'?-1:1)/24);break;case'KeyF':setFree(!free);break;case'KeyH':document.body.classList.toggle('hideui');break;case'KeyP':capture();break;case'KeyC':saveCamera();break;case'KeyD':$('stats').checked=!$('stats').checked;$('debug').classList.toggle('hidden',!$('stats').checked);break;}});
 document.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{if(document.hidden){setPlaying(false);keys.clear();}});document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);});for(let n of['pointerup','pointercancel','lostpointercapture'])b.addEventListener(n,()=>keys.delete(b.dataset.key));});window.addEventListener('resize',resize);
}
async function init(){
 const data=JSON.parse($('recipe').textContent);renderer=new THREE.WebGLRenderer({canvas:$('viewport'),antialias:true,powerPreference:'high-performance',preserveDrawingBuffer:true});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.info.autoReset=false;
 renderer.debug.onShaderError=(gl,program,vs,fs)=>{let text=[gl.getProgramInfoLog(program),gl.getShaderInfoLog(vs),gl.getShaderInfoLog(fs)].filter(Boolean).join('\n');shaderErrors.push(text);fatal(new Error('GLSL: '+text));};
 $('viewport').addEventListener('webglcontextlost',e=>{e.preventDefault();setPlaying(false);toast('Ngữ cảnh GPU đã mất. Đang chờ trình duyệt khôi phục…');});$('viewport').addEventListener('webglcontextrestored',()=>location.reload());
 camera=new THREE.PerspectiveCamera(46,innerWidth/innerHeight,.1,2200);await initAssets(data,(v,name)=>{$('loadbar').style.width=(v*45)+'%';$('loadtext').textContent='Dựng mô hình: '+name;});
 world=createWorld();let pmrem=new THREE.PMREMGenerator(renderer),env=new RoomEnvironment(),target=pmrem.fromScene(env,.04);world.scene.environment=target.texture;world.scene.environmentIntensity=.22;env.dispose();pmrem.dispose();
 pipeline=new FilmPipeline(renderer,world.scene,camera);
 controls=new OrbitControls(camera,renderer.domElement);controls.enabled=false;controls.enableDamping=false;controls.minDistance=.6;controls.maxDistance=500;controls.maxPolarAngle=Math.PI-.02;controls.panSpeed=.7;controls.rotateSpeed=.55;controls.zoomSpeed=.8;setQuality('balanced');renderer.setSize(160,90,false);
 for(let i=0;i<chapters.length;i++){let c=chapters[i],tt=c.id==='hospital'?101:c.id==='street'?132:c.start+5;world.setLocation(c.id);filmCamera(camera,tt,gentle);world.update(tt,camera,gentle);$('loadtext').textContent='Chuẩn bị bộ đổ bóng: '+c.short;$('loadbar').style.width=(48+i*6)+'%';await renderer.compileAsync(world.scene,camera);renderer.render(world.scene,camera);await new Promise(r=>setTimeout(r,0));}
 resize();wireUI();world.setLocation('bridge');filmCamera(camera,0,gentle);world.update(0,camera,gentle);draw(0);$('loadbar').style.width='100%';$('loading').classList.add('hidden');
 let gl=renderer.getContext(),ext=gl.getExtension('WEBGL_debug_renderer_info'),gpu=ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER);
 window.__B52={ready:true,version:'2.0.0',history:historyRecords,seed:19721218,chapters,shots:shots.map(s=>({a:s.a,b:s.b,id:s.id,name:s.name,fov:s.fov})),measurements,gpu,design:data.design_v2,layout:world.layoutAudit,collapse:world.collapse.audit,physics:world.blasts.map(b=>({start:b.start,location:b.root.parent.name,...b.audit})),gpuTiming:()=>pipeline.info(),seek(value){dismissIntro();setPlaying(false);seek(Number(value));draw(0);},play(value=true){dismissIntro();setPlaying(value);},setFree,setQuality,capture,render:()=>draw(0),setGentle(v){gentle=!!v;$('gentle').checked=gentle;},state(){return{t:currentTime(),location:world.location,playing,free,speed,shot:shots.indexOf(shotAt(t)),position:camera.position.toArray(),target:controls.target.toArray(),fov:camera.fov,damageCount:world.damageCount,visibleFragments:world.blasts.filter(b=>b.root.parent.visible&&b.age>=0).reduce((n,b)=>n+(b.visibleFragments||0),0),shaderErrors:[...shaderErrors],drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,memory:{...renderer.info.memory},programs:renderer.info.programs.length};},samples:()=>frameSamples.slice(),resetSamples(){frameSamples=[];pipeline.resetTiming();},setCamera(p,target,fov){setFree(true);camera.position.set(...p);controls.target.set(...target);if(fov){camera.fov=fov;camera.updateProjectionMatrix();}controls.update();draw(0);}};
 lastNow=performance.now();requestAnimationFrame(animate);console.info('B52_READY',gpu,measurements.b52);
}
init().catch(fatal);
